package com.sentinal.registry.service.EC2;
import com.sentinal.registry.dto.instance.RegisterInstanceRequest;
import com.sentinal.registry.model.instances.InstanceEntity;
import com.sentinal.registry.model.instances.MonitorState;
import com.sentinal.registry.model.user.User;
import com.sentinal.registry.repository.InstanceRepository;
import com.sentinal.registry.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class InstanceService {

    private final InstanceRepository instanceRepository;
    private final UserRepository userRepository;

    public InstanceEntity registerInstance(RegisterInstanceRequest request, String username) {

        // Check if already registered
        if (instanceRepository.existsByInstanceIdAndUserUsername(request.getInstanceId(), username)) {
            throw new RuntimeException("Instance " + request.getInstanceId() + " already registered");
        }

        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UsernameNotFoundException("User not found"));

        InstanceEntity instance = InstanceEntity.builder()
                .instanceId(request.getInstanceId())
                .region(request.getRegion())
                .nickname(request.getNickname())
                .roleArn(request.getRoleArn())
                .externalId(UUID.randomUUID().toString())  // generated by your app
                .state(MonitorState.UP)
                .suspectCount(0)
                .quarantineCount(0)
                .stateChangedAt(System.currentTimeMillis())
                .quarantineDurationMinutes(
                        request.getQuarantineDurationMinutes() != null && request.getQuarantineDurationMinutes() > 0
                                ? request.getQuarantineDurationMinutes() : 5)
                .maxSuspectStrikes(
                        request.getMaxSuspectStrikes() != null && request.getMaxSuspectStrikes() > 0
                                ? request.getMaxSuspectStrikes() : 5)
                .maxQuarantineCycles(
                        request.getMaxQuarantineCycles() != null && request.getMaxQuarantineCycles() > 0
                                ? request.getMaxQuarantineCycles() : 3)
                .user(user)
                .build();

        return instanceRepository.save(instance);
    }

    public List<InstanceEntity> getUserInstances(String username) {
        return instanceRepository.findByUserUsername(username);
    }

    public void deleteInstance(Long id, String username) {
        InstanceEntity instance = instanceRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Instance not found"));

        // Verify the instance belongs to the user
        if (!instance.getUser().getUsername().equals(username)) {
            throw new RuntimeException("Unauthorized to delete this instance");
        }

        instanceRepository.delete(instance);
    }
}
