package com.sentinal.registry.service.EC2;
import com.sentinal.registry.dto.instance.RegisterInstanceRequest;
import com.sentinal.registry.model.instances.InstanceEntity;
import com.sentinal.registry.model.instances.MonitorState;
import com.sentinal.registry.model.user.User;
import com.sentinal.registry.repository.InstanceRepository;
import com.sentinal.registry.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class InstanceService {

    private final InstanceRepository instanceRepository;
    private final UserRepository userRepository;

    public InstanceEntity registerInstance(RegisterInstanceRequest request, String username) {

        // Check if already registered
        if (instanceRepository.existsByInstanceIdAndUserUsername(request.getInstanceId(), username)) {
            throw new RuntimeException("Instance " + request.getInstanceId() + " already registered");
        }

        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UsernameNotFoundException("User not found"));

        InstanceEntity instance = InstanceEntity.builder()
                .instanceId(request.getInstanceId())
                .region(request.getRegion())
                .nickname(request.getNickname())
                .roleArn(request.getRoleArn())
                .externalId(UUID.randomUUID().toString())  // generated by your app
                .state(MonitorState.UP)
                .suspectCount(0)
                .quarantineCount(0)
                .stateChangedAt(System.currentTimeMillis())
                .user(user)
                .build();

        return instanceRepository.save(instance);
    }

    public List<InstanceEntity> getUserInstances(String username) {
        return instanceRepository.findByUserUsername(username);
    }
}
